### ISSUE TITLE
Update the favicon

### ISSUE THREAD

**Issue by thekingslee** [nworiekingslee/Easy-pomodoro#12]

**Comment by Olagammal** [comment]
@nworiekingslee Can you please specify what icon should be used for favicon?

**Comment by thekingslee** [comment]
Okay,I will soon @Olagammal

**Comment by thekingslee** [comment]
Use this

![Easy Pomodoro](https://user-images.githubusercontent.com/55883854/177484424-bd6c4d10-e3cc-4af1-a91d-95a899cb8e3e.svg)
